### PR TITLE
added infix search parameter

### PR DESCRIPTION
**Pull request by Nikodym7373**
## Change Summary
added infix search parameter

## PR Checklist

- [ x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by Nikodym7373** [comment]
the addition of the infix parameter does not seem to have any effect. Any hints?

**Comment by programVeins** [comment]
Infix parameter seems to work properly for me (works best by combing maxExtraPrefix/Suffix), I've refactored the code a little bit and have created a PR #25 @Nikodym7373 Thank you so much for your contribution. Can you checkout the latest PR and let me know if your it is still not working for your use case?

**Comment by Nikodym7373** [comment]
Im sorry, but I dont see any effect of the InFix parameter.  Can you provide the test case you are using?

**Comment by jasonbosco** [comment]
Added in #30

**Pull request closed without merging**
